Added support for Grails 2.0.0.RC1

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -8,7 +8,23 @@ BIN_DIR=$(cd $(dirname $0); pwd) # absolute path
 # parse args
 BUILD_DIR=$1
 CACHE_DIR=$2
-GRAILS_VERSION="1.3.7"
+
+if [ ! -f $BUILD_DIR/application.properties ] ; then
+    echo "-----> application.properties not found. This file is required. Build failed."
+    echo " !     Failed to build app"
+    exit 1
+fi
+    
+GRAILS_VERSION=`grep app.grails.version $BUILD_DIR/application.properties | sed -e 's/app.grails.version=\(.*\)$/\1/g'`
+
+echo "-----> Grails $GRAILS_VERSION app detected"
+
+if [ ! "$GRAILS_VERSION" == "1.3.7" ] && [ ! "$GRAILS_VERSION" == "2.0.0.RC1" ] ; then
+    echo "-----> Grails version $GRAILS_VERSION not supported."
+    echo "       Only Grails 1.3.7 and 2.0.0.RC1 are currently supported"
+    echo " !     Failed to build app"
+    exit 1
+fi
 
 if [ ! -d $CACHE_DIR ] ; then
   mkdir $CACHE_DIR
@@ -38,7 +54,11 @@ export PATH=$GRAILS_HOME/bin:$PATH
 cd $BUILD_DIR
 
 # build app
-BUILDCMD="grails -Divy.default.ivy.user.dir=$CACHE_DIR war"
+if [ "$GRAILS_VERSION" = "2.0.0.RC1" ] ; then
+    BUILDCMD_OPT="-plain-output"
+fi
+BUILDCMD="grails $BUILDCMD_OPT -Divy.default.ivy.user.dir=$CACHE_DIR war"
+
 echo "-----> executing $BUILDCMD"
 
 $BUILDCMD 2>&1 | sed -u 's/^/       /'
